name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install the requirements
      run: python install -r requirements.txt
    - name: Run the parser
      run: python parser.py
